Simplify API and improve size allocation
endlessm/maxwell pull request #2
Opened 2018-04-04 13:09 UTC by xjuan

Replace canvas-id packing property with widget's name property

https://phabricator.endlessm.com/T21883

2018-04-04 18:32 UTC, cosimoc requested changes

2018-04-04 18:32 UTC, cosimoc commented on src/maxwell-web-view.c
> +  GString *script = g_string_new ("");
You could initialize this only if `priv->script_loaded` and then check for `if (script)` below; that would make things a bit cleaner IMO. (Also true for the other cases touched by this commit.)

2018-04-04 18:32 UTC, cosimoc commented on src/maxwell-web-view.c
> +    child_update_visibility (webview, GTK_WIDGET (object));
This function is already robust to `!priv->script_loaded`, so you don't need the extra check here.

2018-04-04 18:33 UTC, cosimoc commented
Looks great to me other than those two comments.

2018-04-05 14:34 UTC, xjuan commented
Ok, good I just fixed those two things

2018-04-05 14:34 UTC, merged