Make all drawing call asynchronous
endlessm/maxwell pull request #4
Opened 2018-04-18 13:49 UTC by xjuan

This improves responsiveness a lot.

2018-04-18 16:04 UTC, tchx84 commented
I tested this on a real app with flapjack, and the difference is quite noticeable, e.g. no more visual artifacts and lag when resizing the screen.

2018-04-18 21:38 UTC, ptomato requested changes
The code looks fine, but now when I run it with flapjack the Maxwell canvas is entirely blank.

2018-04-18 21:38 UTC, ptomato commented on src/maxwell-web-view.c
> +  guint         pixbuf_count; /* Pixbuf counter, used ad id */
typo: ad -> as

2018-04-18 21:38 UTC, ptomato commented on src/maxwell-web-view.js
> +    /* Remove all request that where drawn */
typo: where -> were

2018-04-18 21:38 UTC, ptomato commented on src/maxwell-web-view.js
> +    xhr.maxwell = { child: child, x: x, y: y, width: width, height: height };
optional: If we have a new enough JavaScriptCore you may be able to use the nice ES6 syntax: `xhr.maxwell = {child, x, y, width, height};`

2018-04-19 19:38 UTC, tchx84 commented
Tested this again, and I can't reproduce the issue @ptomato mentioned. It looks OK here. BUT, I noticed some "on_maxwell_uri_scheme_request /%d" message trashing the log.

2018-04-19 21:46 UTC, ptomato approved these changes
We discussed that we'll merge this, but still continue to investigate what the issue is with my machine.

2018-04-19 21:46 UTC, merged